### PR TITLE
Fix/61 use clevercsv over csv library

### LINKED ISSUE #61: sniff_delimiter returns wrong delimiter when csv contains a lot of JSON
I haven't put together an example that reproduces this yet, as the real-world example csv contains JSON cells with around 26000 characters each of privileged information and I haven't made a test file of comparable size yet.

The expected delimiter is `","`, but `sniff_delimiter` returns `":"`. If I pass the entire byte stream to `csv.Sniffer()` it gets the delimiter right, so I guess `1024 * 4` bytes isn't enough to disambiguate the `","` from the `":"` as possible delimiters with all that JSON in the mix. I'm sure we don't want to pass the entire byte stream every time, and increasing the number of bytes we pass seems like an endless game of whack-a-mole as file sizes get larger.

For our use-case, where the delimiter is known beforehand, it might be enough to just have `parse` accept an `expected_delimiter` argument that gets passed down to the `ParseVisitor` and down to `parse_csv`, calling `sniff_delimiter` as needed if `expected_delimiter` isn't specified. This wouldn't solve the problem for users that don't have prior knowledge of the delimiter, though.

### PR DESCRIPTION
**Pull request by jbcooley7**
Fixes #61.

Per my discussion with @thomasjohns in the issue, I replaced the usage of the standard library `csv` module with [clevercsv](https://github.com/alan-turing-institute/CleverCSV). This was mostly a simple swap-out, but I did need to add some logic since `clevercsv` returns an empty string when it can't find a delimiter in the file, rather than raising an error as the `csv` module does.

Locally, `nox` was failing to run tests due to missing `clevercsv` in the test context. I think @Andres-Endava ran into the same issue in his recent PR, and solved it by adding `cchardet` to the installed dependencies in the `noxfile`. It seems odd to me to specify unpinned dependencies there, especially when the same dependencies are pinned in the `requirements.txt`. Even if we pinned them in the `noxfile`, we'd have to take pains to ensure the versions stayed synced with the `requirements.txt`. So I also updated the `noxfile` to just install from the requirements file. This does increase the time it takes nox to run, so I'm happy to add a `requirements-test.txt` file to alleviate that if it's deemed preferable.

Also, after reading the nox docs, I wasn't convinced that the pandas version is actually being changed simply by having `@nox.parametrize` decorating the `test` function. Following the example from their [docs](https://nox.thea.codes/en/stable/tutorial.html#parametrization), I added an explicit pandas import. @thomasjohns curious to hear background on that configuration and if I'm overlooking something.

### CODE REVIEW

**Comment by Andres-Endava** [comment]
I think you should add the `requirements-test.txt` file. In some computers tests can take a long time.

**Comment by jbcooley7** [comment]
@Andres-Endava I've been thinking about it, and it's just odd that `cchardet` and `cleverscv` would have to be included in the `requirements-test.txt`. I would expect them to be in the `requirements-lib.txt` (or whatever we call the library's non-test related requirements). I don't like the idea of duplicating those dependencies in `requirements-test` and `requirements-lib`, because they'd have to be manually kept in sync, and we could just use `session.install` with pinned versions in the `noxfile`. I also considered a `requirements-common.txt` to contain `cchardet` and `clevercsv`, to be referenced by `requirements-test` and `requirements-lib`, but that seems like a huge mess.

**Review by Andres-Endava — APPROVED** [review]

**Comment by jbcooley7** [comment]
@thomasjohns do you have thoughts or a preference on the approach to the requirements?

**Comment by thomasjohns** [comment]
Hey @jbcooley7 . I don't have a well informed preference since I haven't reviewed best practices for how to make `setup.py`, `tox`/`nox`, and `requirements.txt` work well together in awhile.

Though given my current mental model, I would vote for maintainability, i.e. not repeating dependencies in different requirements files, over performance of running `nox` (in that sense I like the `session.install("-r", "requirements.txt")`). I usually don't run `nox` except maybe right before making a PR or in CI. While iterating, I'd tend to just run `mypy` or `pytest` directly. I wonder if other developers do the same? Also, I think the performance hit for `nox` should only occur the first time it is run, since it has to create the virtual environments from scratch. Additional runs of `nox` should be fast and reuse existing virtual environments if I recall correctly.

I wonder if the way the noxfile has `session.install("-e", ".")` i.e. `pip install -e .` using `setup.py` is interfering with things too ... (the `setup.py` file also specifies some dependencies)

Thanks for the PR by the way! It looks good to me.

**Comment by jbcooley7** [comment]
Ok, I'll leave things as they are in this PR then. You could be right about the `setup.py`, maybe adding `cchardet` there would have been the solution to @Andres-Endava's problem. But it still has the issue around maintainability to go adding things there with pinned versions. Thanks for the feedback, @thomasjohns!

**Pull request merged**
